# 生产者
server:
  port: 8081

spring:
  application:
    name: active-MQ-produce
  activemq:
    # MQ服务器地址
    broker-url: tcp://49.232.61.212:61616
    user: admin
    password: admin
  jms:
    # false = Queue true = Topic 默认false
    pub-sub-domain: false

# 定义队列
queue: laughing-queue


