# 消费者
server:
  port: 8095

spring:
  application:
    name: active-MQ-produce-topic
  activemq:
    # MQ服务器地址
    broker-url: tcp://49.232.61.212:61616
    user: admin
    password: admin
  jms:
    # false = Queue true = Topic 默认false
    pub-sub-domain: true

# 定义主题
topic: laughing-topic



